name: .NET Build & Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    permissions:
      checks: write
      pull-requests: write
      contents: read
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        dotnet: [8.0.x]

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ matrix.dotnet }}

    - name: Restore dependencies
      run: dotnet restore EdTechApp/EdTechApp.csproj

    - name: Build
      run: dotnet build EdTechApp/EdTechApp.csproj --no-restore --configuration Release

    - name: Run tests
      run: dotnet test EdTechApp.Tests/EdTechApp.Tests.csproj --no-build --logger "trx;LogFileName=test_results.trx" --results-directory ./TestResults

    - name: Publish Test Results
      if: always()
      uses: dorny/test-reporter@v1
      with:
        name: .NET Tests
        path: TestResults/test_results.trx
        reporter: dotnet-trx

